name: Linting & Tests
on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Install Rust Stable
        uses: dtolnay/rust-toolchain@stable
      - name: Install typos
        uses: taiki-e/install-action@typos
      - name: Check typos
        run: typos .
      - name: Check code formatting
        run: cargo fmt --check
  build:
    name: Testing
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
    - name: Install Rust Stable
      uses: dtolnay/rust-toolchain@stable
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
